version: '3.8'

services:
  # Frontend with Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: obs_frontend_prod
    restart: always
    ports:
      - "80:80"
    networks:
      - obs_network

networks:
  obs_network:
    driver: bridge
